# Generated by Django 4.2.21 on 2025-05-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('quantity', models.FloatField(default=0)),
                ('unit', models.CharField(max_length=20)),
                ('expiry_date', models.DateField(null=True)),
                ('last_stocked', models.DateField(auto_now=True)),
            ],
        ),
    ]
