# Generated by Django 4.2.21 on 2025-05-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipesDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('category_path', models.CharField(blank=True, max_length=100, null=True)),
                ('prep_time', models.IntegerField(blank=True, null=True)),
                ('servings', models.IntegerField(blank=True, null=True)),
                ('ingredients', models.CharField(blank=True, max_length=500, null=True)),
                ('instructions', models.CharField(max_length=5000, null=True)),
                ('recipe_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
