# Generated by Django 4.2.21 on 2025-05-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipesdb_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesdb',
            name='prep_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
