# Generated by Django 4.2.21 on 2025-05-28 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipesdb_prep_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipesdb',
            old_name='category_path',
            new_name='category',
        ),
    ]
