# Generated by Django 4.2.21 on 2025-05-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_category_path_recipesdb_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesdb',
            name='prep_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
