# Generated by Django 4.2.21 on 2025-06-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipesdb_prep_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipesdb',
            name='source',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recipesdb',
            name='instructions',
            field=models.JSONField(max_length=5000, null=True),
        ),
    ]
