# Generated by Django 4.2.21 on 2025-06-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipesdb_source_alter_recipesdb_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesdb',
            name='source',
            field=models.CharField(default='internal', max_length=20),
        ),
    ]
